name: Release Build FTP
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/sleeptale-backend
            git pull origin release-build-backend
            npm ci
            npm run build
            pm2 reload sleeptale-backend || pm2 start dist/main.js --name sleeptale-backend
   
