name: Release Build
on:
  workflow_dispatch:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Generate static site
        run: npm run generate
        working-directory: ./frontend

      - name: Show files after build
        run: ls -la frontend/.output/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          folder: frontend/.output/public
          clean: true
          clean-exclude: |
            "CNAME"
            ".gitattributes"
            ".nojekyll"
          single-commit: true
